// import * as React from 'react';
import Footer from '@/client-components/Footer/Footer';
import Navbar from '@/client-components/Navbar/index';

import '@/styles/globals-client.css';

export const metadata = {
  title: 'eLearning',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <div className="client-class">{children}</div>;
}
